name: Build and Test

on:
  push:
  pull_request:

jobs:
  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: packages/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install packages
        run: bun install

      - name: Test
        run: bun test
